# Generated by Django 3.2.3 on 2021-08-07 13:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import validators.beat_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat_notes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('title', models.CharField(max_length=30, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5), validators.beat_validators.first_latter_capital, validators.beat_validators.no_bad_words])),
                ('description', models.TextField(max_length=500, null=True, validators=[validators.beat_validators.no_bad_words])),
                ('cover_image', models.ImageField(blank=True, upload_to='covers')),
                ('beat_notes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='beats.beatnotes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeatPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beats.beat')),
            ],
        ),
    ]
