# Generated by Django 3.2.3 on 2021-08-11 09:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
