# Generated by Django 3.2.3 on 2021-07-31 17:08

from django.db import migrations, models
import omega_beats.omega_beats_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('omega_beats_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='omegabeatsuser',
            managers=[
                ('objects', omega_beats.omega_beats_auth.models.OmegaBeatManager()),
            ],
        ),
        migrations.AddField(
            model_name='omegabeatsuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
