# Generated by Django 3.2.3 on 2021-08-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega_beats_auth', '0002_auto_20210731_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('avatar_image', models.ImageField(upload_to='avatars')),
            ],
        ),
    ]
