# Generated by Django 3.2.3 on 2021-08-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega_beats_auth', '0004_auto_20210801_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='{ { description } }', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, default='{ { username } }', max_length=30),
        ),
    ]
