# Generated by Django 3.2.3 on 2021-08-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega_beats_auth', '0005_auto_20210801_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='default description', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, default='default username', max_length=30),
        ),
    ]
