# Generated by Django 3.2.3 on 2021-08-11 08:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omega_beats_auth', '0006_auto_20210807_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
