# Generated by Django 3.2.3 on 2021-07-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_beatnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='beat_notes',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.beatnotes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beat',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='beat',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
