# Generated by Django 3.2.3 on 2021-07-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210721_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='id',
        ),
        migrations.AlterField(
            model_name='beat',
            name='beat_notes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.beatnotes'),
        ),
    ]
