# Generated by Django 3.2.3 on 2021-07-23 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210721_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='cover_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='covers'),
            preserve_default=False,
        ),
    ]
