# Generated by Django 3.2.3 on 2021-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_beat_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
