# Generated by Django 3.2.3 on 2021-07-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_beat_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
