# Generated by Django 3.2.3 on 2021-07-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_beat_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beat')),
            ],
        ),
    ]
