# Generated by Django 3.2.3 on 2021-08-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_beat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
