# Generated by Django 3.2.3 on 2021-08-03 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_alter_beat_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='omega_beats_auth.omegabeatsuser'),
            preserve_default=False,
        ),
    ]
