# Generated by Django 3.2.3 on 2021-08-07 11:17

import django.core.validators
from django.db import migrations, models
import validators.beat_validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_beat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='description',
            field=models.TextField(max_length=500, null=True, validators=[validators.beat_validators.no_bad_words]),
        ),
        migrations.AlterField(
            model_name='beat',
            name='title',
            field=models.CharField(max_length=30, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5), validators.beat_validators.first_latter_capital, validators.beat_validators.no_bad_words]),
        ),
    ]
